In [1]:
'''
Data Source - UNICEF DATA WAREHOUSE: https://data.unicef.org/resources/data_explorer/unicef_f/?ag=UNICEF&df=GLOBAL_DATAFLOW&ver=1.0&dq=KEN+MLI+SLE+SOM.MNCH+COD_ACUTE_HEPATITIS_A+COD_ACUTE_HEPATITIS_B+COD_AFRICAN_TRYPANOSOMIASIS+COD_ALCOHOL_USE_DISORDERS+COD_ALZHEIMER_DISEASE_AND_OTHER_DEMENTIAS+COD_APPENDICITIS+COD_ASTHMA+COD_BLADDER_CANCER+COD_BRAIN_AND_NERVOUS_SYSTEM_CANCERS+COD_BREAST_CANCER+COD_CARDIOMYOPATHY_MYOCARDITIS_ENDOCARDITIS+COD_CERVIX_UTERI_CANCER+COD_CHLAMYDIA+COD_CHRONIC_OBSTRUCTIVE_PULMONARY_DISEASE+COD_CIRRHOSIS_OF_THE_LIVER+COD_COLLECTIVE_VIOLENCE_AND_LEGAL_INTERVENTION+COD_COLON_AND_RECTUM_CANCERS+COD_CONGENITAL_ANOMALIES+COD_CYSTICERCOSIS+COD_DENGUE+COD_DIABETES_MELLITUS+COD_DIARRHOEAL_DISEASES+COD_DIPHTHERIA+COD_DROWNING+COD_DRUG_USE_DISORDERS+COD_ECHINOCOCCOSIS+COD_ENCEPHALITIS+COD_EPILEPSY+COD_EXPOSURE_TO_MECHANICAL_FORCES+COD_FALLS+COD_FIRE_HEAT_AND_HOT_SUBSTANCES+COD_GALLBLADDER_AND_BILIARY_DISEASES+COD_GENITAL_HERPES+COD_GONORRHOEA+COD_HIV_AIDS+COD_HYPERTENSIVE_HEART_DISEASE+COD_IDIOPATHIC_INTELLECTUAL_DISABILITY+COD_INFLAMMATORY_BOWEL_DISEASE+COD_INTERPERSONAL_VIOLENCE+COD_IRON_DEFICIENCY_ANAEMIA+COD_ISCHAEMIC_HEART_DISEASE+COD_KIDNEY_CANCER+COD_KIDNEY_DISEASES+COD_LEISHMANIASIS+COD_LEUKAEMIA+COD_LIVER_CANCER+COD_LOWER_RESPIRATORY_INFECTIONS+COD_LYMPHOMAS_MULTIPLE_MYELOMA+COD_MALARIA+COD_MATERNAL_CONDITIONS+COD_MEASLES+COD_MELANOMA_AND_OTHER_SKIN_CANCERS+COD_MENINGITIS+COD_MESOTHELIOMA+COD_MOUTH_AND_OROPHARYNX_CANCERS+COD_NATURAL_DISASTERS+COD_OESOPHAGUS_CANCER+COD_OVARY_CANCER+COD_PANCREAS_CANCER+COD_PANCREATITIS+COD_PARALYTIC_ILEUS_AND_INTESTINAL_OBSTRUCTION+COD_PEPTIC_ULCER_DISEASE+COD_POISONINGS+COD_PROTEIN_ENERGY_MALNUTRITION+COD_RABIES+COD_RHEUMATIC_HEART_DISEASE+COD_ROAD_INJURY+COD_SELF_HARM+COD_SICKLE_CELL_DISORDERS_AND_TRAIT+COD_SKIN_DISEASES+COD_STOMACH_CANCER+COD_STROKE+COD_SYPHILIS+COD_TESTICULAR_CANCER+COD_TETANUS+COD_THALASSAEMIAS+COD_THYROID_CANCER+COD_TRACHEA_BRONCHUS_LUNG_CANCERS+COD_TRICHOMONIASIS+COD_TUBERCULOSIS+COD_UPPER_RESPIRATORY_INFECTIONS+COD_WHOOPING_COUGH+COD_YELLOW_FEVER+MNCH_ABR+MNCH_ADO_ALCOHOL+MNCH_ADO_INSUFF_PHYS+MNCH_ADO_TOBACCO+MNCH_ANC1+MNCH_ANC4+MNCH_BIRTH18+MNCH_CSEC+MNCH_DEMAND_FP+MNCH_DIARCARE+MNCH_INFDEC+MNCH_INSTDEL+MNCH_IPTP+MNCH_ITN+MNCH_ITN2+MNCH_ITNOWN+MNCH_ITNPREG+MNCH_LIFE_EXPECTANCY+MNCH_LTR_MATERNAL_DEATH+MNCH_MATERNAL_DEATHS+MNCH_MLRACT+MNCH_MLRCARE+MNCH_MLRDIAG+MNCH_MMR+MNCH_ORS+MNCH_ORSZINC+MNCH_ORTCF+MNCH_PNCMOM+MNCH_PNCNB+MNCH_PNEUCARE+MNCH_PNEUMORT+MNCH_SAB+MNCH_UHC+MNCH_UHC_RMNCH+MNCH_ZINC+MNCH_CSEC_TND+MNCH_INSTDEL_TND.F+M+_T.&startPeriod=2000&endPeriod=2026
'''

'\nData Source - UNICEF DATA WAREHOUSE: https://data.unicef.org/resources/data_explorer/unicef_f/?ag=UNICEF&df=GLOBAL_DATAFLOW&ver=1.0&dq=KEN+MLI+SLE+SOM.MNCH+COD_ACUTE_HEPATITIS_A+COD_ACUTE_HEPATITIS_B+COD_AFRICAN_TRYPANOSOMIASIS+COD_ALCOHOL_USE_DISORDERS+COD_ALZHEIMER_DISEASE_AND_OTHER_DEMENTIAS+COD_APPENDICITIS+COD_ASTHMA+COD_BLADDER_CANCER+COD_BRAIN_AND_NERVOUS_SYSTEM_CANCERS+COD_BREAST_CANCER+COD_CARDIOMYOPATHY_MYOCARDITIS_ENDOCARDITIS+COD_CERVIX_UTERI_CANCER+COD_CHLAMYDIA+COD_CHRONIC_OBSTRUCTIVE_PULMONARY_DISEASE+COD_CIRRHOSIS_OF_THE_LIVER+COD_COLLECTIVE_VIOLENCE_AND_LEGAL_INTERVENTION+COD_COLON_AND_RECTUM_CANCERS+COD_CONGENITAL_ANOMALIES+COD_CYSTICERCOSIS+COD_DENGUE+COD_DIABETES_MELLITUS+COD_DIARRHOEAL_DISEASES+COD_DIPHTHERIA+COD_DROWNING+COD_DRUG_USE_DISORDERS+COD_ECHINOCOCCOSIS+COD_ENCEPHALITIS+COD_EPILEPSY+COD_EXPOSURE_TO_MECHANICAL_FORCES+COD_FALLS+COD_FIRE_HEAT_AND_HOT_SUBSTANCES+COD_GALLBLADDER_AND_BILIARY_DISEASES+COD_GENITAL_HERPES+COD_GONORRHOEA+COD_HIV_AIDS+COD_HYPERTENSIVE_HEART_DISEASE+COD_IDIOPATHIC_INTELLECTUAL_DISABILITY+COD_INFLAMMATORY_BOWEL_DISEASE+COD_INTERPERSONAL_VIOLENCE+COD_IRON_DEFICIENCY_ANAEMIA+COD_ISCHAEMIC_HEART_DISEASE+COD_KIDNEY_CANCER+COD_KIDNEY_DISEASES+COD_LEISHMANIASIS+COD_LEUKAEMIA+COD_LIVER_CANCER+COD_LOWER_RESPIRATORY_INFECTIONS+COD_LYMPHOMAS_MULTIPLE_MYELOMA+COD_MALARIA+COD_MATERNAL_CONDITIONS+COD_MEASLES+COD_MELANOMA_AND_OTHER_SKIN_CANCERS+COD_MENINGITIS+COD_MESOTHELIOMA+COD_MOUTH_AND_OROPHARYNX_CANCERS+COD_NATURAL_DISASTERS+COD_OESOPHAGUS_CANCER+COD_OVARY_CANCER+COD_PANCREAS_CANCER+COD_PANCREATITIS+COD_PARALYTIC_ILEUS_AND_INTESTINAL_OBSTRUCTION+COD_PEPTIC_ULCER_DISEASE+COD_POISONINGS+COD_PROTEIN_ENERGY_MALNUTRITION+COD_RABIES+COD_RHEUMATIC_HEART_DISEASE+COD_ROAD_INJURY+COD_SELF_HARM+COD_SICKLE_CELL_DISORDERS_AND_TRAIT+COD_SKIN_DISEASES+COD_STOMACH_CANCER+COD_STROKE+COD_SYPHILIS+COD_TESTICULAR_CANCER+COD_TETANUS+COD_THALASSAEMIAS+COD_THYROID_CANCER+COD_TRACHEA_BRONCHUS_LUNG_CANCERS+COD_TRICHOMONIASIS+COD_TUBERCULOSIS+COD_UPPER_RESPIRATORY_INFECTIONS+COD_WHOOPING_COUGH+COD_YELLOW_FEVER+MNCH_ABR+MNCH_ADO_ALCOHOL+MNCH_ADO_INSUFF_PHYS+MNCH_ADO_TOBACCO+MNCH_ANC1+MNCH_ANC4+MNCH_BIRTH18+MNCH_CSEC+MNCH_DEMAND_FP+MNCH_DIARCARE+MNCH_INFDEC+MNCH_INSTDEL+MNCH_IPTP+MNCH_ITN+MNCH_ITN2+MNCH_ITNOWN+MNCH_ITNPREG+MNCH_LIFE_EXPECTANCY+MNCH_LTR_MATERNAL_DEATH+MNCH_MATERNAL_DEATHS+MNCH_MLRACT+MNCH_MLRCARE+MNCH_MLRDIAG+MNCH_MMR+MNCH_ORS+MNCH_ORSZINC+MNCH_ORTCF+MNCH_PNCMOM+MNCH_PNCNB+MNCH_PNEUCARE+MNCH_PNEUMORT+MNCH_SAB+MNCH_UHC+MNCH_UHC_RMNCH+MNCH_ZINC+MNCH_CSEC_TND+MNCH_INSTDEL_TND.F+M+_T.&startPeriod=2000&endPeriod=2026\n'

In [2]:
import pandas as pd
import duckdb

In [3]:
df = pd.read_excel("sample_data/GLOBAL_DATAFLOW_2000-2026.xlsx", sheet_name='Unicef data')

In [4]:
# Convert to lowercase and replace spaces with dashes
df.columns = df.columns.str.lower().str.replace(' ', '_')

df.head()

,geographic_area,indicator,sex,2024,2023,2022,2021,2020,2019,2018,...,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000
0,Mali,Percentage of adolescents (aged 15-19 years) w...,Female,-,-,-,-,-,4.4,-,...,-,-,-,-,-,-,-,-,-,-
1,Mali,Percentage of adolescents (aged 15-19 years) w...,Male,-,-,-,-,-,5.5,-,...,-,-,-,-,-,-,-,-,-,-
2,Mali,Percentage of adolescents (aged 15-19 years) w...,Total,-,-,-,-,-,5,-,...,-,-,-,-,-,-,-,-,-,-
3,Mali,Antenatal care 1+ visit - percentage of women ...,Total,69.3,-,-,84.2,-,-,79.5,...,-,-,-,70.4,-,-,-,-,56.8,-
4,Mali,Antenatal care 4+ visits - percentage of women...,Total,51.3,-,-,44.7,-,-,43.3,...,-,-,-,35.4,-,-,-,-,29.9,-

In [5]:
# Convert year columns to numeric and replace with zero for nulls
columns_to_cast = list(range(2000, 2025))
year_cols = [str(x) for x in columns_to_cast]

df[year_cols] = df[year_cols].apply(pd.to_numeric, errors='coerce').fillna(0).astype(int)

In [6]:
df.head()

,geographic_area,indicator,sex,2024,2023,2022,2021,2020,2019,2018,...,2009,2008,2007,2006,2005,2004,2003,2002,2001,2000
0,Mali,Percentage of adolescents (aged 15-19 years) w...,Female,0,0,0,0,0,4,0,...,0,0,0,0,0,0,0,0,0,0
1,Mali,Percentage of adolescents (aged 15-19 years) w...,Male,0,0,0,0,0,5,0,...,0,0,0,0,0,0,0,0,0,0
2,Mali,Percentage of adolescents (aged 15-19 years) w...,Total,0,0,0,0,0,5,0,...,0,0,0,0,0,0,0,0,0,0
3,Mali,Antenatal care 1+ visit - percentage of women ...,Total,69,0,0,84,0,0,79,...,0,0,0,70,0,0,0,0,56,0
4,Mali,Antenatal care 4+ visits - percentage of women...,Total,51,0,0,44,0,0,43,...,0,0,0,35,0,0,0,0,29,0

In [7]:
# Identify the columns to keep as identifiers
id_vars = [col for col in df.columns if col not in year_cols]

# Melt the dataframe
df_melted = pd.melt(
    df,
    id_vars=id_vars, #  The non-year columns  serve as the identifier variables
    value_vars=year_cols,
    var_name='year',
    value_name='mncah_total'
)

# Display the melted dataframe
df_melted.head()

,geographic_area,indicator,sex,year,mncah_total
0,Mali,Percentage of adolescents (aged 15-19 years) w...,Female,2000,0
1,Mali,Percentage of adolescents (aged 15-19 years) w...,Male,2000,0
2,Mali,Percentage of adolescents (aged 15-19 years) w...,Total,2000,0
3,Mali,Antenatal care 1+ visit - percentage of women ...,Total,2000,0
4,Mali,Antenatal care 4+ visits - percentage of women...,Total,2000,0

In [8]:
# Save the DataFrame to a CSV file
df_melted.to_csv('sample_data/mncah_data_2000_2025.csv', index=False)

In [9]:
df_summary = duckdb.query("""
                              SELECT geographic_area, SUM(mncah_total)
                              FROM df_melted
                              GROUP BY geographic_area, mncah_total
                              ORDER BY mncah_total
                              DESC LIMIT 10
                              """).to_df()
df_summary

  geographic_area  sum(mncah_total)
0           Kenya            7518.0
1           Kenya            7484.0
2           Kenya            7406.0
3           Kenya            7339.0
4           Kenya            7182.0
5           Kenya            7076.0
6           Kenya            6918.0
7           Kenya            6854.0
8           Kenya            6598.0
9           Kenya            6410.0